### ISSUE TITLE
Learning from Data (Project Progress 3)

### ISSUE THREAD

**Issue by Kozmocha** [UNCG-CSE/Volvo_Truck_Analytics#61]
**PRESENTATION DATE: 12/03/2019**

**T2 Task by Member (10 pts)**
- Formulate the question.
- Why was the question asked?
**T3 Progress made towards the task. (30 pts)**
    - **T3.1 Describe the method (15 pts)**
       - Basic machine learning modeling/Analytical approach/Dashboard implementation.
       - What was done to solve for the question?
    - **T3.2 Description of the results/outcomes (15 pts)**
    - What were the outcomes?
    - What are their implications?

**Comment by IBatsios** [comment]
Can you quickly determine an engine problem based on temperature expectations?

The question was asked because it could be a cost effective approach to finding a problem within the engine.
