### ISSUE TITLE
Repository & Code Cleanup

### ISSUE THREAD

**Issue by Kozmocha** [UNCG-CSE/Volvo_Truck_Analytics#64]
Before the final presentation / submission date, we should do the following:
- Remove **all** branches that are not being used.
- Remove **all unused** Jupyter Notebooks.
- "Comment in" or use markdown to place author name(s) of all used Notebooks.
- Update repository's README to a final, attractive and easy-to-follow version.
- Remove any unused documentation.
- Organize any used documentation.
- Label all Issues that have not been completed with "wontfix" and then close them (we'll probably never touch this again once it's over).

**Comment by ghost** [comment]
We completed as many of these as we could without breaking anything.
